[project]
name = "ne-kadar"
version = "0.1.0"
description = "Fiyat tahmin etme oyunu"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.5",
    "fastapi>=0.115.7",
    "requests>=2.32.3",
    "uvicorn>=0.34.0",
]
